### PR TITLE
Website

### LINKED ISSUE #40: Housekeeping
I'm going to create a `vancouver` team for the nodeschool org on GitHub, so I'm not the bottleneck on administration and event planning. **Organizer volunteers needed**!
## Tasks
- [x] Create a `vancouver` team on nodeschool
- [x] Add organizers to the team
- [x] Add organizers to ti.to
- [x] Simplify our README.md
- [x] Update our [chapters file](https://github.com/nodeschool/nodeschool.github.io/blob/source/chapters/vancouver.json)
- [x] Update the info on our website

### PR DESCRIPTION
**Pull request by lvivier**
Closes #40 

I thought to update our website at [nodeschool.io/vancouver](http://nodeschool.io/vancouver) 

Feedback welcome. When I get to it I'd like to put the upcoming event right on the web site thru the Ti.to API.

GitHub has added some new configuration choices for Pages sites, so this PR also moves the site to the /docs folder, rather than a separate branch. I thought this would make it easier/more obvious for ppl to contribute to the website.

### CODE REVIEW

**Comment by forivall** [comment]
[Preview](https://rawgit.com/nodeschool/vancouver/website/docs/index.html)

Looks good for a start, although I dont have any kind of design ideas for this yet. I feel like we can also use this as an impetus to bring in the logo from #32 / #2.

As long as it's better than [Toronto's](http://nodeschool.io/toronto/), right?

**Comment by forivall** [comment]
[Preview](https://rawgit.com/nodeschool/vancouver/website/docs/index.html)

Looks good for a start, although I dont have any kind of design ideas for this yet. I feel like we can also use this as an impetus to bring in the logo from #32 / #2.

As long as it's better than [Toronto's](http://nodeschool.io/toronto/), right?

**Comment by forivall** [comment]
[Preview](https://rawgit.com/nodeschool/vancouver/website/docs/index.html)

Looks good for a start, although I dont have any kind of design ideas for this yet. I feel like we can also use this as an impetus to bring in the logo from #32 / #2.

As long as it's better than [Toronto's](http://nodeschool.io/toronto/), right?

**Comment by lvivier** [comment]
:+1: to preview…yeah I realize it's no great shakes visually or otherwise, I just thought to get a fresh start, get it out of gh_pages where more ppl might come across it and iterate. Be nice to get that logo going on too.

**Comment by lvivier** [comment]
Merrging…PRs welcome to improve this thing!

**Pull request merged**
