### PR TITLE
Move 2018 to second block, add airg to meetup

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Review by keywordnew — APPROVED** [review]
Stoked about the addition of airG!

And thank you for flipping the order and putting the now-lengthy past sessions at the bottom! 💯

**Comment by halkeye** [comment]
Yea the upcoming/past thing was always out of date so I figured this was easier

**Comment by halkeye** [comment]
@nfg has a better gmaps link

**Comment by nfg** [comment]
https://goo.gl/maps/sAxJhoE4YW62 , to the right of the Sportsbar sign. I can take a better picture if desired.

**Comment by keywordnew** [comment]
@nfg literally it's behind the glass panes to the right of the Sportsbar sign? 🙂

**Pull request merged**
