### PR TITLE
Move oct and Nov to the past, add oct and nov to next year

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by halkeye** [comment]
We still need create meetup events. I'll confirm Clio for January.

@chowdhurian how picky are you about the meetup bodies. Is January node school spring series?

**Comment by keywordnew** [comment]
@halkeye Created two meetup events for Jan and Feb. Not announced. Venues filled as TBD. Feel free to update at your discretion! 💯

> how picky are you about the meetup bodies.

Sorry, I don't understand... 🙏🏽

> Is January node school spring series?

Called it the Spring Is Here Series 🌻

Doesn't have to be, can def change :)

**Review by keywordnew — APPROVED** [review]
LGTM! 💥

**Comment by halkeye** [comment]
> Sorry, I don't understand... 🙏🏽

it was more of "Can gavin who is less creative create the events" but if you did it, then awesome.

**Comment by keywordnew** [comment]
I cloned the last one, made it about Spring, added emojis, then cloned that one again.

**Pull request merged**
