### PR TITLE
Add venues till September

### PR DESCRIPTION
**Pull request by keywordnew**

### CODE REVIEW

**Comment by halkeye** [comment]
I thought they couldn't do sundays.

**Comment by keywordnew** [comment]
The confirmed dates are for Saturdays.

**Comment by halkeye** [comment]
oh shoot for some reason i thought may 19th was sunday. It was saturday all along.

LGTM.

Is it confirmed? Can I let tracey we have something booked and to not worry about it?

**Comment by keywordnew** [comment]
It's all but confirmed, in that I'm waiting for Shanna at Elysian to email that they've blocked off the dates.

**Comment by keywordnew** [comment]
The dates are booked!

**Comment by daffl** [comment]
Will the events be added to [the meetup group](https://www.meetup.com/nodeschool-vancouver/) as well?

**Comment by daffl** [comment]
Well, turns out that #73 came in the same time I wrote my previous comment 😉

**Comment by keywordnew** [comment]
Thanks for keeping us on track @daffl!

**Pull request merged**
